services:
  redis-cluster:
    container_name: redis-cluster
    image: 'zhangchaoyy/redis-cluster:7.2.5'
    environment:
     IP: ${REDIS_CLUSTER_IP}
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        redis_version: '7.2.5'
    hostname: server
    ports:
      - '7000-7050:7000-7050'
      - '5000-5010:5000-5010'
